name: Build Deploy

# 在main分支发生push事件时触发。
on:
  push:
    branches:
      - main
      - master
    paths:
      - "docs/**" # 只当docs文件夹中的文件发生变化时触发
  workflow_dispatch:

# 设置环境变量
env:
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: build project ⚗️
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Jod"
      - name: Run docs-scraper 🚀
        env:
          API_KEY: ${{ secrets.MEILISEARCH_API_KEY  }}
          CONFIG_FILE_PATH: ${{ github.workspace }}/docs/public/data/config.json
          HOST_URL: ${{ secrets.MEILISEARCH_HOST_URL  }}
        run: |
          echo " 🏃‍♂️ Pulling docker images 🏃‍♂️  "
          docker pull getmeili/docs-scraper:v0.12.8
          echo " 🏃‍♀️ Running docs-scraper 🏃‍♀️  "
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $CONFIG_FILE_PATH:/docs-scraper/config.json \
            getmeili/docs-scraper:v0.12.8 pipenv run ./docs_scraper config.json
